/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "primary": "#004ac6",
        "outline": "#737686",
        "on-secondary-fixed-variant": "#3323cc",
        "on-primary-fixed": "#00174b",
        "error": "#ba1a1a",
        "secondary-fixed": "#e2dfff",
        "outline-variant": "#c3c6d7",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#0b1c30",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "on-secondary-container": "#fffbff",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#645efb",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary-container": "#e9f0ff",
        "on-secondary-fixed": "#0f0069",
        "tertiary": "#46566c",
        "surface-container": "#eceef0",
        "surface-tint": "#0053db",
        "secondary-fixed-dim": "#c3c0ff",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "tertiary-container": "#5e6e85",
        "on-primary-container": "#eeefff",
        "secondary": "#4b41e1",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#1e3a8a',
        }
      },
      spacing: {
        inspector_width: '320px',
        sidebar_width: '240px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'label-mono': ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
